# Generated by Django 5.1.1 on 2024-10-01 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_band_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='band',
            name='biography',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('R', 'Rock'), ('P', 'Pop'), ('JZ', 'Jazz'), ('HH', 'Hip Hop'), ('RB', 'R And B'), ('CTY', 'Country'), ('D', 'Dance'), ('FR', 'French'), ('OTHER', 'Other')], default='HH', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='official_page',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='year_formed',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)]),
            preserve_default=False,
        ),
    ]
