# Generated by Django 5.1.1 on 2024-10-01 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('sold', models.BooleanField(default=False)),
                ('years', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2024)])),
                ('type', models.CharField(choices=[('DISK', 'Disk'), ('RECORD', 'Record'), ('CLOTHING', 'Clothing'), ('POSTER', 'Poster'), ('MISC', 'Misc')], max_length=100)),
            ],
        ),
    ]
